version: '3.8'

services:
  nestjs-modules-fcm:
    image: devrecipies/nestjs-modules:latest
    container_name: nestjs-modules-fcm
    ports:
      - '5656:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Firebase configuration - add your actual values to .env file
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
    env_file:
      - .env
    restart: unless-stopped
